### ISSUE TITLE
Implementar https://github.com/codenautas/pg-promise-strict/blob/master/docs/additions.md

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/sql-promise#1]
Agregar las funciones que controlan cantidades según https://github.com/codenautas/pg-promise-strict/blob/master/docs/additions.md

**Comment by diegoefe** [comment]
Listo

**Comment by emilioplatzer** [comment]
No anda para https://github.com/codenautas/sqlite-promise/commit/86a0ed219cdc4d745fdd75b0bd8b8d5ca3a49bde

**Comment by diegoefe** [comment]
Ahora anda. Cuando puedas verificarlo, cerralo.

**Comment by emilioplatzer** [comment]
Aparentemente sí.
